### ISSUE TITLE
Reproducible example issue tmap 

### ISSUE THREAD

**Issue by suzannemaas** [U-Shift/cyclingpotential-hack#17] opened 2020-09-25 08:36 UTC
Running into an issue with the reproducible example (using R v3.6).

While package 'tmap' is successfully installed and unpacked, I'm not managing to get it loaded successfully: 
> install.packages("tmap")
"package ‘tmap’ successfully unpacked and MD5 sums checked"
> library(tmap)
"Error: package or namespace load failed for ‘tmap’ in namespaceExport(ns, exports):
 undefined exports: providers"

Tried to add 'dependencies = TRUE' to the install.packages command, but didn't solve the issue.

**Comment by Robinlovelace** [comment] 2020-09-25 08:43
Thanks for the report @suzannemaas, I think I know what the problem is...

**Comment by Robinlovelace** [comment] 2020-09-25 08:45
Could you try running this?:

```
remotes::install_version(package = "XML", version = "3.99-0.3")
```

Or re-install a more recent version of R (4.0.0 is the latest).

Details: https://github.com/mtennekes/tmap/issues/150

**Comment by suzannemaas** [comment] 2020-09-25 08:58
Thanks @Robinlovelace Thought that may be the case. Installing new version now, let's see :)

**Comment by suzannemaas** [comment] 2020-09-25 09:23
A race against the clock, but success :) thanks again @Robinlovelace

**Comment by Robinlovelace** [comment] 2020-09-25 10:39
Great to hear @suzannemaas ! Please close the issue if it's fixed : )

**Closed as completed** 2020-09-25 10:46 UTC
